services:
  proxy:
    build:
      context: . #Build from Dockerfile in the current directory
      dockerfile: Dockerfile
    container_name: armor_proxy
    ports:
      - "8080:8080" #Port mapping between host and container
    networks:
      - very_secure
    volumes:
      - shared:/certs

  client:
    image: alpine:latest
    container_name: armor_client
    user: root
    command: ["sh", "-c", "${CLIENT_COMMAND}"]
    depends_on:
      - proxy #Wait for proxy to start
    networks:
      - very_secure
    volumes:
      - shared:/certs

networks:
  very_secure:
    driver: bridge

volumes:
  shared_data:
