name: Test e2e client to website flow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
      
      - name: Build and start services
        run: |
          docker-compose -f docker-compose.yml up --build -d
      
      - name: Wait for services to start
        run: sleep 30

      - name: Check client logs
        run: docker-compose logs client

      - name: Verify expected outcome
        run: |
          # Check if curl returned the expected result
          CURL_RESULT=$(docker logs armor_client)

          if echo "$CURL_RESULT" | grep -q "HTTP/1.1 403 Forbidden"; then
            echo "Results look fine, as it was blocked with HTTP 403"
            exit 1
          else
            echo "Something's not right, the request was not blocked with HTTP 403..."
            exit 1
          fi
    
      - name: Clean up
        if: always()
        run: docker-compose down