name: Test e2e client to website flow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
      
      - name: Build and start services
        env:
          CMD: apk add --no-cache ca-certificates curl && mkdir -p /usr/local/share/ca-certificates && while [ ! -f /certs/ca.crt ]; do echo 'Waiting for CA certificate...'; sleep 2; done && cp /certs/ca.crt /usr/local/share/ca-certificates/ca.crt && update-ca-certificates && sleep 3 && curl -v -x http://proxy:4090 -X TRACE https://google.com.com
        run: |
          docker-compose -f docker-compose.yml up --build -d

      - name: Wait for the client to get the CA certificate
        run: sleep 10

      - name: Check client logs
        run: docker-compose logs client

      - name: Verify expected outcome
        run: |
          docker logs armor_client 2>&1 | tee logs.txt
          grep -q "HTTP/1.1 405 Not Allowed" logs.txt
    
      - name: Clean up
        if: always()
        run: docker-compose down